Repository human6014/LaserCrush, pull requests merged in 2024-02, with the labels that each got.

#159 Feat : Install item pos | Fix : Dropped item reset, Mobile screen
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/RayManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Feat

#160 Feat : Launcher second subline | Fix: Installed item pos
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Feat

#161 Feat : 4 branch prism | Fix : Item additional energy
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch4.prefab
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch4.prefab.meta
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism4.prefab
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism4.prefab.meta
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab.meta
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Fix, Feat

#162 Feat : 충돌 시 에너지 정지
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
Labels: Feat

#164 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
Labels: Merge

#165 Feat : 게임 로직 수정
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Feat

#166 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Merge

#167 Revert from human6014_Desktop to main
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Merge

#168 Feat : Energy image
  Assets/GoogleMobileAds/Editor/Resources/PlaceholderAds/Banners/ADAPTIVE.prefab
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_High_2.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_High_2.wav.meta
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_High_3.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_High_3.wav.meta
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Low_2.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Low_3.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Low_3.wav.meta
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Med_2.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Med_3.wav
  Assets/Import Asset/Cute UI _ Interact Sound Effects Pack/AUDIO/Pop/Bottle/SFX_Pop_Bottle_Med_3.wav.meta
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/Displayer/ImageSlideDisplayer.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Firework_Explosion_2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Firework_Explosion_2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Player_Collect_Coin_1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Player_Collect_Coin_1.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/레이저 소리_1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/레이저 소리_1.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
Labels: Feat

#169 Fix : Admob covers UI
  Assets/GoogleMobileAds/Editor/Resources/PlaceholderAds/Banners/ADAPTIVE.prefab
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Test/AdaptiveBanner.cs
  Assets/MyAsset/03. Script/Test/AdaptiveBanner.cs.meta
  Assets/MyAsset/09. Data/Audio Data.asset
Labels: Fix

#172 Feat : Sound connect | Bug : Energy, Item
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/08. Audio/Clip/BG/Old.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_1.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_1.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_2.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_2.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_3.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_3.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_4.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_4.mp3.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDamage.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDamage.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDestroy.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDestroy.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_StageChange.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_StageChange.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Firework_Explosion_2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Firework_Explosion_2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/Temp/SFX_Player_Collect_Coin_1.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ButtonClick.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ButtonClick.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemAcquired.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemAcquired.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemBatchFail.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemBatchFail.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemBatchSuccess.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemBatchSuccess.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemClick.mp3
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemClick.mp3.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDown.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDown.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDrag.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDrag.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDropped.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemDropped.wav.meta
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemUp.wav
  Assets/MyAsset/08. Audio/Clip/UISE/SFX_ItemUp.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
Labels: Bug, Feat

#174 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_1.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_3.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_3.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_4.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_4.wav.meta
Labels: Merge

#177 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Merge

#178 Feat : Donate UI | Refactor : Installed item data | Fix : Save & Load
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs.meta
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/Controller/DonateController.cs
  Assets/MyAsset/03. Script/UI/Controller/DonateController.cs.meta
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism2Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism3Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab
  Assets/MyAsset/08. Audio/Clip/BG/Old.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_1.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_1.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_2.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_2.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_3.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_3.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_4.mp3
  Assets/MyAsset/08. Audio/Clip/BG/Old/BGM_4.mp3.meta
  Assets/MyAsset/09. Data/Audio Data.asset
  Assets/MyAsset/09. Data/InstalledItem Data.asset
  Assets/MyAsset/09. Data/InstalledItem Data.asset.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Fix, Refactor, Feat

#179 Fix : Build error (admob)
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/Test/AdaptiveBanner.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사버튼.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사버튼.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Fix

#182 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/tem1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/tem1.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/tem2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/tem2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_3.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_3.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사_4.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징_1.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징_1.wav.meta
Labels: Merge

#185 Merge from main to human6014_Desktop
  Assets/MyAsset/08. Audio/Clip/NormalSE/블럭-파괴_3.ogg
  Assets/MyAsset/08. Audio/Clip/NormalSE/블럭-파괴_3.ogg.meta
Labels: Merge

#186 Feat : 오디오 파일 링크 수정
  Assets/MyAsset/09. Data/Audio Data.asset
  ProjectSettings/ProjectSettings.asset
Labels: Feat

#192 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/09. Data/InstalledItem Data.asset
  ProjectSettings/ProjectSettings.asset
Labels: Merge

#200 Merge from main to human6014_Desktop
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Button/Btn_Square03_White1.png
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Button/Btn_Square03_White1.png.meta
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs.meta
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/ObjectPoolManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/New Folder.meta
  Assets/MyAsset/New Folder/b3d0412a258727267cc715da06c79550.jpg
  Assets/MyAsset/New Folder/b3d0412a258727267cc715da06c79550.jpg.meta
  Assets/MyAsset/New Folder/carrd resources.jpg
  Assets/MyAsset/New Folder/carrd resources.jpg.meta
Labels: Merge

#201 Feat : Boss blcok | Fix : Laser reflect, Subline match laser
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/Block.prefab.meta
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Fix, Feat

#203 Adjust : 수치 조정
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
Labels: Adjust

#205 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/EEntityType.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
Labels: Merge

#209 Feat : 블럭 데미지 사운드 교체
  Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/MA_PashaStriker_Plop_4.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/MA_PashaStriker_Plop_4.wav.meta
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Feat

#211 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/BossBlockVer2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/BossBlockVer2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/BossStage.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/BossStage.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/MA_PashaStriker_Plop_4.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/MA_PashaStriker_Plop_4.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Merge

#212 Merge from human6014 to TestLogic_Main
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
  ProjectSettings/ProjectSettings.asset
Labels: Merge

#213 Feat : Audio
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
  Assets/MyAsset/08. Audio/Clip/NormalSE/MA_PashaStriker_Plop_4.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockHit.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockHit.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlockVer2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlockVer2.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossStage.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossStage.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_EnergyCharge.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_EnergyCharge.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_LaunchLaser.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_LaunchLaser.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/tem2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/블럭 데미지_3.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/블럭 데미지_3.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/에너지 차징.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
Labels: Feat

#214 Feat : Game play style change
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs
  Assets/MyAsset/03. Script/Entity/Floor.cs.meta
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/09. Data/InstalledItem Data.asset
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
Labels: Feat

#215 Feat : 보스블럭 사운드 추가
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlock.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlock.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlockVer2.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/보스 블럭 생성.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/보스 블럭 생성.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
Labels: Feat

#217 Feat : Damage UI | Refactor : Laser time check
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/UIAnimationPlayer.cs
  Assets/MyAsset/03. Script/UI/UIAnimationPlayer.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: Refactor, Feat

#216 Feat : 보스 블럭 이미지 추가
  Assets/Import Asset/BlockPng.meta
  Assets/Import Asset/BlockPng/기본 해골.png
  Assets/Import Asset/BlockPng/기본 해골.png.meta
  Assets/Import Asset/BlockPng/데미지 해골.png
  Assets/Import Asset/BlockPng/데미지 해골.png.meta
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
Labels: Feat

#218 Merge from main to human6014_Desktop
  Assets/Import Asset/BlockPng.meta
  Assets/Import Asset/BlockPng/기본 해골.png
  Assets/Import Asset/BlockPng/기본 해골.png.meta
  Assets/Import Asset/BlockPng/데미지 해골.png
  Assets/Import Asset/BlockPng/데미지 해골.png.meta
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
Labels: Merge

#219 Feat : Grid line, Concurrent audio, Boss block image
  Assets/Import Asset/BlockPng/기본 해골.png.meta
  Assets/Import Asset/BlockPng/데미지 해골.png.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/AudioManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab
  Assets/MyAsset/04. Prefab/Line/GridLine.prefab
  Assets/MyAsset/04. Prefab/UI/Notify_Demo_Red.prefab
  Assets/MyAsset/06. Material/GridLineMaterial.mat
  Assets/MyAsset/06. Material/GridLineMaterial.mat.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDamage.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BlockDamage.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossBlock.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossStage.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossStage.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사버튼.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/발사버튼.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/보스 블럭 생성.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/보스 블럭 생성.wav.meta
  Assets/MyAsset/10. Shader/dottedLine.shadergraph
  ProjectSettings/AudioManager.asset
Labels: Feat

#222 Feat : Damage Text
  Assets/Import Asset/BlockPng.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/UI/Controller/TutorialPanelController.cs
  Assets/MyAsset/05. Sprite/기본 해골.png
  Assets/MyAsset/05. Sprite/기본 해골.png.meta
  Assets/MyAsset/05. Sprite/데미지 해골.png
  Assets/MyAsset/05. Sprite/데미지 해골.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: Feat

#223 Feat : Game icon, capture | Fix : Damage text color
  Assets/Editor/EditorScript/SimpleCapture.cs
  Assets/Editor/EditorScript/SimpleCapture.cs.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/05. Sprite/GameIcon.jpg
  Assets/MyAsset/05. Sprite/GameIcon.jpg.meta
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyNumberController1.overrideController
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyNumberController1.overrideController.meta
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyNumberController2.overrideController
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyNumberController2.overrideController.meta
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyTextColor1.anim
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyTextColor1.anim.meta
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyTextColor2.anim
  Assets/MyAsset/07. Animation/UI/HighlightNumber/HighlightOnlyTextColor2.anim.meta
  Assets/ScreenShot.meta
  Assets/ScreenShot/2024-02-20_01-47-28.png
  Assets/ScreenShot/2024-02-20_01-47-28.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Feat

#224 Adjust : 데미지 공식 수정
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Adjust

#226 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Merge

#229 Feat : 보스 블럭 기믹 추가 | Adjust : 밸런스 조정
  Assets/MyAsset/03. Script/Entity/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Feat, Adjust

#233 Adjust : 밸런스 조절 | Refactor : 코드 리펙토링
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
Labels: Refactor, Adjust

#234 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
Labels: Merge

#236 Adjust : 벨런스 조절
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Adjust

#238 ReFactor : 코드 리펙토링
  Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
Labels: Adjust

#240 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  ProjectSettings/ProjectSettings.asset
Labels: Merge

#241 Feat : Damage UI, Boss audio, boss age data | Fix : Time UI
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Data/BlockProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ObjectPoolManager.cs
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossSound.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_BossSound.wav.meta
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_MoveDownBlock.wav
  Assets/MyAsset/08. Audio/Clip/NormalSE/SFX_MoveDownBlock.wav.meta
  Assets/MyAsset/09. Data/Audio Data.asset
  Assets/MyAsset/09. Data/ItemProbability Data.asset
Labels: Fix, Feat

#242 Fix : Block probability
  Assets/MyAsset/03. Script/Data/BlockProbabilityData.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/09. Data/BlockProbabilityData.asset
Labels: Fix

#243 Refactor : 코드 리펙토링
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
Labels: Refactor

#244 Fix : Gap block and wall
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
Labels: Fix

#245 Fix : 코드 수정이 적용 안된부분 다시 수정
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
Labels: Fix

#246 Feat : 블럭 스테이지기반 HP생성 가중치 추가
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
Labels: Feat

#247 Feat : 튜토리얼 이미지 추가
  Assets/MyAsset/05. Sprite/Tutorial/8.png
  Assets/MyAsset/05. Sprite/Tutorial/8.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/new4.png
  Assets/MyAsset/05. Sprite/Tutorial/new4.png.meta
Labels: Feat

#248 Refactor : 안 쓰는 코드및 변수 제거
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
Labels: Refactor

#249 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
  Assets/MyAsset/05. Sprite/Tutorial/8.png
  Assets/MyAsset/05. Sprite/Tutorial/8.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/new4.png
  Assets/MyAsset/05. Sprite/Tutorial/new4.png.meta
Labels: Merge

#250 Fix : Gap block and wall | Feat : Audio
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/02. Settings/Renderer2D.asset
  Assets/MyAsset/02. Settings/ShaderVariants.shadervariants
  Assets/MyAsset/02. Settings/ShaderVariants.shadervariants.meta
  Assets/MyAsset/02. Settings/UniversalRP.asset
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Block/BlockParticle.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/AudioManager.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/08. Audio/Clip/BG/BGM_Unicorn.mp3
  Assets/MyAsset/08. Audio/Clip/BG/BGM_Unicorn.mp3.meta
  Assets/MyAsset/08. Audio/Clip/BG/BGM_Unicorn_1.mp3
  Assets/MyAsset/08. Audio/Clip/BG/BGM_Unicorn_1.mp3.meta
  Assets/MyAsset/09. Data/Audio Data.asset
  Assets/ScreenShot.meta
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Feat

#251 Fix : Last tutorial image | Refactor : Entity
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Data/BlockData.cs
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/UI/Controller/TutorialPanelController.cs
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism2Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism3Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Refactor

#252 Feat : Optimize texture, Tutorial
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Icon_ItemIcons_(x2)/ItemIcon_64/Icon_ItemIcon_Energy.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Icon_ItemIcons_(x2)/ItemIcon_64/Icon_ItemIcon_Setting.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Icon_ItemIcons_(x2)/ItemIcon_64/Icon_ItemIcon_Shop.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Icon_PictoIcons_(x2)/PictoIcon_64/Icon_PictoIcon_Control_Pause.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Icon_PictoIcons_(x2)/PictoIcon_64/Icon_PictoIcon_Gift.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Label/label_oval_Demo_Brown.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Label/label_ribbon01_Demo_brown.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Label/label_ribbon01_Demo_green.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Components/Slider/slider02_frame_Demo.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Demo/Demo_UI/Notify_Bg_White.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Demo/Demo_image/Image_Effect_Rotate_White.Png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Demo/Demo_image/Slider04_IconType_Frame.png.meta
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Sprites/Demo/Demo_image/Slider04_IconType_Frame_Line.png.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab
  Assets/MyAsset/05. Sprite/BossDefault.png
  Assets/MyAsset/05. Sprite/BossDefault.png.meta
  Assets/MyAsset/05. Sprite/BossHit.png
  Assets/MyAsset/05. Sprite/BossHit.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/1.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/2.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/3.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/4.png
  Assets/MyAsset/05. Sprite/Tutorial/4.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/5.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/6.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/7.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/8.png.meta
  Assets/MyAsset/05. Sprite/Tutorial/new4.png
  Assets/MyAsset/05. Sprite/Tutorial/new4.png.meta
  Assets/ScreenShot.meta
  ProjectSettings/ProjectSettings.asset
Labels: Feat

#253 Refactor : Block movedown, Object pool
  Assets/MyAsset/03. Script/Controller/BlockParticleController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/03. Script/Manager/ObjectPoolManager.cs
  Assets/MyAsset/03. Script/UI/Controller/FloatingTextController.cs
  Assets/MyAsset/04. Prefab/Block/Block.prefab
  Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
Labels: Refactor

#254 Fix : Mobile touch | Refactor : Unused feature remove
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/07. Animation/Item/InstalledItem/FixedItemNotice.anim
  Assets/MyAsset/07. Animation/Item/InstalledItem/FixedItemNotice.anim.meta
  Assets/MyAsset/07. Animation/Item/InstalledItem/InstalledItemController.controller
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Refactor

#256 Fix : LaserManager 버그
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Fix

#258 Fix : Damage calc, Boss block sound sync
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/EEntityType.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/AudioManager.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Fix

#259 Refactor : 안쓰는 함수및 변수 삭제
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Interface/ICollisionable.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
Labels: Refactor

#260 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Interface/ICollisionable.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Entity/Wall.cs
Labels: Merge

#262 Feat : Game icon change
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/ThirdParty/AdaptiveBanner.cs
  Assets/MyAsset/03. Script/UI/Controller/DonateController.cs
  Assets/MyAsset/05. Sprite/GameIcon.jpg
  ProjectSettings/ProjectSettings.asset
Labels: Feat

#263 Merge from main to human6014_Desktop
  Assets/MyAsset/05. Sprite/Title.jpg
  Assets/MyAsset/05. Sprite/Title.jpg.meta
  ProjectSettings/ProjectSettings.asset
Labels: Merge

#265 Feat : Hit audio play, Launcher pos | Refactor : Unused data remove | Fix : Launcher pos clamp
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Data/BlockData.cs
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs
  Assets/MyAsset/03. Script/Data/InstalledItemData.cs.meta
  Assets/MyAsset/03. Script/Data/LaserData.cs
  Assets/MyAsset/03. Script/Entity/Block/Block.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Manager/AudioManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/ThirdParty/AdaptiveBanner.cs
  Assets/MyAsset/09. Data/Block Data.asset
  Assets/MyAsset/09. Data/InstalledItem Data.asset
  Assets/MyAsset/09. Data/InstalledItem Data.asset.meta
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Refactor, Feat

#266 Fix : Screen bug
  Assets/MyAsset/03. Script/Manager/GameSettingManager.cs
  Assets/MyAsset/03. Script/ThirdParty/AdaptiveBanner.cs
  ProjectSettings/ProjectSettings.asset
Labels: Fix

#267 Feat : Tutorial image
  Assets/MyAsset/05. Sprite/Icon/Icon_SkillIcon_Energe.Png.meta
  Assets/MyAsset/05. Sprite/Tutorial/1.png
  Assets/MyAsset/05. Sprite/Tutorial/2.png
  Assets/MyAsset/05. Sprite/Tutorial/3.png
  Assets/MyAsset/05. Sprite/Tutorial/4.png
  Assets/MyAsset/05. Sprite/Tutorial/5.png
  Assets/MyAsset/05. Sprite/Tutorial/6.png
  Assets/MyAsset/05. Sprite/Tutorial/7.png
  Assets/MyAsset/05. Sprite/Tutorial/8.png
  Assets/MyAsset/05. Sprite/Tutorial/new4..png
  Assets/MyAsset/05. Sprite/Tutorial/new4..png.meta
  ProjectSettings/ProjectSettings.asset
Labels: Feat
