Repository human6014/LaserCrush, pull requests merged in 2024-01, with the labels that each got.

#137 Feat : Sub line | Fix : Item using count
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/UI/Controller/PatronageController.cs
  Assets/MyAsset/03. Script/UI/Displayer/PanelDisplayer.cs
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism2Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism3Branch.prefab
  Assets/MyAsset/04. Prefab/Line/SubLine.prefab
  Assets/MyAsset/06. Material/SubLineMaterial.mat
  Assets/MyAsset/06. Material/SubLineMaterial.mat.meta
  Assets/MyAsset/10. Shader.meta
  Assets/MyAsset/10. Shader/dottedLine.shadergraph
  Assets/MyAsset/10. Shader/dottedLine.shadergraph.meta
  Assets/MyAsset/ClassDiagram1.cd
  Assets/MyAsset/ClassDiagram1.cd.meta
Labels: Fix, Feat

#138 Feat : auto save & load | Fix : Launcher image, Reset score | Refactor : Instantiate func
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/InputObject/DragTransfromObject.cs
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Controller/ToolbarController.cs
  Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Extension/ExtensionVector2.cs
  Assets/MyAsset/03. Script/Manager/AudioManager.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs.meta
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/AcquiredItemUI.cs
  Assets/MyAsset/03. Script/UI/Controller/SettingPanelController.cs
  Assets/MyAsset/03. Script/UI/Displayer/ReDisplayer.cs
  Assets/MyAsset/03. Script/UI/Displayer/SliderDisplayer.cs
  Assets/MyAsset/03. Script/UI/Displayer/SliderDisplayer.cs.meta
  Assets/MyAsset/03. Script/UI/Displayer/TextDisplayer.cs
  Assets/MyAsset/03. Script/UI/Receiver/SliderReceiver.cs
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedEnergy.prefab
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism1.prefab
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism2.prefab
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism3.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism2Branch.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism3Branch.prefab
  Assets/MyAsset/04. Prefab/Line/SubLine.prefab
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/10. Shader/dottedLine.shadergraph
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_iOS.json
Labels: Fix, Refactor, Feat

#139 Feat : 데미지 로직 추가
  Assets/IronSource.meta
  Assets/IronSource/Editor.meta
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab.meta
  Assets/Layer Lab/GUI-TheStone.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Feat

#141 Merge from main to human6014_Desktop
  Assets/IronSource.meta
  Assets/IronSource/Editor.meta
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab.meta
  Assets/Layer Lab/GUI-TheStone.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Merge

#142 Feat : IAP, Save encryption & load decryption | Fix : Build error
  Assets/Editor/EditorScript/DataEditor.cs
  Assets/Editor/EditorScript/DataEditor.cs.meta
  Assets/Import Asset/NonResourceAsset.meta
  Assets/Import Asset/ResourceAsset.meta
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab.meta
  Assets/Layer Lab/GUI-TheStone.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/02. Settings/UniversalRenderPipelineGlobalSettings.asset
  Assets/MyAsset/02. Settings/UniversalRenderPipelineGlobalSettings.asset.meta
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/Controller/PatronageController.cs
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch1.prefab
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch2.prefab
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch3.prefab
  Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism1.prefab
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/MyAsset/04. Prefab/UI/FloatingText.prefab
  Assets/Resources/IAPProductCatalog.json
  Assets/Scripts/UnityPurchasing/generated/AppleStoreKitTestTangle.cs
  Assets/Scripts/UnityPurchasing/generated/AppleTangle.cs
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Fix, Feat

#146 Fix : Laser
  Assets/GoogleMobileAds/Resources/GoogleMobileAdsSettings.asset
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/03. Script/Test/GoogleAdMob.cs
  Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab
  Assets/Plugins/Android/GoogleMobileAdsPlugin.androidlib/AndroidManifest.xml
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
Labels: Fix

#148 Merge from main to human6014_Desktop
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Merge

#149 Feat : Game board image | Fix : Game over load, Launcher fire, Laser dispose
  Assets/Import Asset/NonResourceAsset.meta
  Assets/Import Asset/ResourceAsset.meta
  Assets/IronSource.meta
  Assets/IronSource/Editor.meta
  Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta
  Assets/Layer Lab.meta
  Assets/Layer Lab/GUI-TheStone.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI.meta
  Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Controller/SubLineController.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/ItemManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch1.prefab
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch2.prefab
  Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch3.prefab
  Assets/MyAsset/05. Sprite/frame_stageframe_Demo_n.png
  Assets/MyAsset/05. Sprite/frame_stageframe_Demo_n.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: Fix, Feat

#151 Feat : UI, Best score
  Assets/Import Asset/Layer Lab/GUI-TheStone/Prefabs/Prefabs_Component_ActionText/_PrefabsPanel_ActionText.prefab
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Fonts/Changa-Bold SDF.asset
  Assets/Import Asset/Layer Lab/GUI-TheStone/ResourceData/Fonts/Changa-Bold_Underlay SDF.asset
  Assets/Import Asset/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Manager/DataManager.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/UIManager.cs
  Assets/MyAsset/03. Script/UI/Displayer/TextDisplayer.cs
  Assets/MyAsset/04. Prefab/UI/Label_Flag_White.prefab
  Assets/MyAsset/04. Prefab/UI/Label_Flag_White.prefab.meta
Labels: Feat

#152 Merge from main to human6014_Desktop
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/BlockManager.cs
Labels: Merge

#155 Adjust : 게임 수치 조정 | Feat : 프리즘 충돌 시 에너지 차징 로직 추가
  Assets/GoogleMobileAds/Resources/GoogleMobileAdsSettings.asset
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
Labels: Feat, Adjust

#156 Merge from main to human6014_Desktop
  Assets/GoogleMobileAds/Resources/GoogleMobileAdsSettings.asset
  Assets/MyAsset/03. Script/Entity/Block.cs
  Assets/MyAsset/03. Script/Entity/Energy.cs
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/09. Data/ItemProbability Data.asset
  Assets/MyAsset/09. Data/Laser Data.asset
Labels: Merge

#157 Feat : Laser pooling
  Assets/MyAsset/01. Scenes/Main Scene.unity
  Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs
  Assets/MyAsset/03. Script/Entity/Laser.cs
  Assets/MyAsset/03. Script/Manager/GameManager.cs
  Assets/MyAsset/03. Script/Manager/LaserManager.cs
Labels: Feat
